//TO ADD ITEM TO CART
export const CART_ADD_ITEM="CART_ADD_ITEM";
//TO REMOVE ITEM FROM CART
export const CART_REMOVE_ITEM="CART_REMOVE_ITEM";
//TO SAVE SHIPPING ADDRESS OF USER
export const CART_SAVE_SHIPPING_ADDRESS="CART_SAVE_SHIPPING_ADDRESS";
export const CART_UNSAVE_SHIPPING_ADDRESS="CART_SAVE_SHIPPING_ADDRESS";
//TO SAVE PAYMENT METHOD OF USER
export const CART_SAVE_PAYMENT_METHOD="CART_SAVE_PAYMENT_METHOD";