//CONSTANTS FOR CREATING ORDER LIST
export const  ORDER_CREATE_REQUEST="ORDER_CREATE_REQUEST";
export const  ORDER_CREATE_SUCCESS="ORDER_CREATE_SUCCESS";
export const  ORDER_CREATE_FAIL="ORDER_CREATE_FAIL";
export const  ORDER_CREATE_RESET="ORDER_CREATE_RESET";

//CONSTANTS FOR GETTING ORDER LIST
export const  ORDERList_GET_REQUEST="ORDERList_GET_REQUEST";
export const  ORDERList_GET_SUCCESS="ORDERList_GET_SUCCESS";
export const  ORDERList_GET_FAIL="ORDERList_GET_FAIL";

//CONSTANTS FOR HANDLING PAYMENT VIA PAYPAL
export const  ORDER_PAYPAL_PAYMENT_REQUEST="ORDER_PAYPAL_PAYMENT_REQUEST";
export const  ORDER_PAYPAL_PAYMENT_SUCCESS="ORDER_PAYPAL_PAYMENT_SUCCESS";
export const  ORDER_PAYPAL_PAYMENT_FAIL="ORDER_PAYPAL_PAYMENT_FAIL";
export const  ORDER_PAYPAL_PAYMENT_RESET="ORDER_PAYPAL_PAYMENT_RESET";

//CONSTANTS FOR HANDLING PAYMENT WITHOUTB PAYPAL
export const  ORDER_NONPAYPAL_PAYMENT_REQUEST="ORDER_NONPAYPAL_PAYMENT_REQUEST";
export const  ORDER_NONPAYPAL_PAYMENT_SUCCESS="ORDER_NONPAYPAL_PAYMENT_SUCCESS";
export const  ORDER_NONPAYPAL_PAYMENT_FAIL="ORDER_NONPAYPAL_PAYMENT_FAIL";
export const  ORDER_NONPAYPAL_PAYMENT_RESET="ORDER_NONPAYPAL_PAYMENT_RESET";

export const CART_EMPTY="CART_EMPTY";

//CONSTANTS FOR GETTING ORDER DETAILS
export const  ORDER_DETAILS_REQUEST="ORDER_DETAILS_REQUEST";
export const  ORDER_DETAILS_SUCCESS="ORDER_DETAILS_SUCCESS";
export const  ORDER_DETAILS_FAIL="ORDER_DETAILS_FAIL";

