
//Constants for fetching all items from backend
export const PRODUCT_LIST_REQUEST='PRODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS='PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL='RODUCT_LIST_FAIL';

//Constants for fetching individual item details from backend
export const PRODUCT_DETAILS_REQUEST='PRODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS='PRODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL='RODUCT_DETAILS_FAIL';

//Constants to deal with comments
export const PRODUCT_REVIEWS_REQUEST='PRODUCT_REVIEWS_REQUEST';
export const PRODUCT_REVIEWS_SUCCESS='PRODUCT_REVIEWS_SUCCESS';
export const PRODUCT_REVIEWS_FAIL='PRODUCT_REVIEWS_FAIL';

//Constants to get product reviews
export const GET_PRODUCT_REVIEWS_REQUEST='GET_PRODUCT_REVIEWS_REQUEST';
export const GET_PRODUCT_REVIEWS_SUCCESS='GET_PRODUCT_REVIEWS_SUCCESS';
export const GET_PRODUCT_REVIEWS_FAIL='GET_PRODUCT_REVIEWS_FAIL';

//Admin Actions with respect to product
//Constants to deal with delete product
export const PRODUCT_DELETE_REQUEST='PRODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS='PRODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETED_DATA='PRODUCT_DELETED_SUCCESS';
export const PRODUCT_DELETE_FAIL='PRODUCT_DELETE_FAIL';

//Constants to deal with edit product
export const PRODUCT_UPDATE_REQUEST='PRODUCT_UPDATE_REQUEST';
export const PRODUCT_UPDATE_SUCCESS='PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_UPDATED_DATA='PRODUCT_UPDATED_SUCCESS';
export const PRODUCT_UPDATE_FAIL='PRODUCT_UPDATE_FAIL';

//Constants to add product
export const PRODUCT_ADD_REQUEST='PRODUCT_ADD_REQUEST';
export const PRODUCT_ADD_SUCCESS='PRODUCT_ADD_SUCCESS';
export const PRODUCT_ADDED_DATA='PRODUCT_ADDED_SUCCESS';
export const PRODUCT_ADD_FAIL='PRODUCT_ADD_FAIL';